---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Gather facts about the system
      setup:

    # Ubuntu/Debian installation
    - name: Install dependencies (Ubuntu/Debian)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG apt Key (Ubuntu/Debian)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker Repository (Ubuntu/Debian)
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker (Ubuntu/Debian)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # CentOS/RHEL installation
    - name: Install yum utils (CentOS/RHEL)
      yum:
        name: yum-utils
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Docker repo (CentOS/RHEL)
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: ansible_os_family == "RedHat"

    - name: Install Docker (CentOS/RHEL)
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_os_family == "RedHat"

    # macOS installation
    - name: Install Homebrew (macOS)
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: ansible_os_family == "Darwin" and ansible_homebrew is not defined

    - name: Install Docker using Homebrew (macOS)
      homebrew_cask:
        name: docker
        state: present
      when: ansible_os_family == "Darwin"

    # Nix installation
    - name: Check if Nix is installed
      command: which nix-env
      register: nix_check
      ignore_errors: yes
      changed_when: false

    - name: Install Docker using Nix
      command: nix-env -iA nixpkgs.docker
      when: nix_check.rc == 0

    # Common tasks for all systems
    - name: Start Docker service (Linux)
      systemd:
        name: docker
        state: started
        enabled: yes
      when: ansible_system == "Linux"

    - name: Start Docker Desktop (macOS)
      command: open -a Docker
      when: ansible_os_family == "Darwin"

    - name: Wait for Docker to start (macOS)
      wait_for:
        path: /var/run/docker.sock
        state: present
        timeout: 60
      when: ansible_os_family == "Darwin"

    - name: Verify Docker installation
      command: docker --version
      register: docker_check
      changed_when: false

    - name: Display Docker version
      debug:
        msg: "Docker installed successfully. Version: {{ docker_check.stdout }}"

    - name: Add user to docker group (Linux)
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: ansible_system == "Linux"

    - name: Reset connection to apply group changes
      meta: reset_connection
